// ============================================================
//  IntPrep.cs -- one-time NASM-side preprocessing of int.asm,
//  applied BEFORE Nasm2Masm.Convert. (C# port of prep_int.py.)
//
//  int.asm is hand-written (not generated by SpitbolBuild), so it carries
//  a few constructs the generated-code path never sees, and it needs the
//  System V -> Microsoft x64 ABI adaptation for its C-call bridge. This
//  class applies all of that; the result then goes through the same
//  Nasm2Masm.Convert as sbl.asm/err.asm, with int_masm.h as the header.
//
//  Usage:
//      string body = Nasm2Masm.Convert(IntPrep.Preprocess(File.ReadAllText("int.asm")));
//      // then prepend int_masm.h, exactly like masm.h for sbl.asm.
// ============================================================

using System.Text.RegularExpressions;

namespace SpitbolTools;

public static class IntPrep
{
    // math_op rewritten for the Microsoft x64 ABI: rbp frame, 16-byte align,
    // 32-byte shadow space, and save/restore of the volatile MINIMAL regs
    // (wa=rcx, wc=rdx) around the libc math call. f_* read/write global reg_ra.
    private const string MathOp =
        "      %macro      math_op 2\n" +
        "      global      %1\n      extern      %2\n%1:\n" +
        "      push  rbp\n      mov   rbp,rsp\n" +
        "      mov   m_word [save_wa],rcx\n      mov   m_word [save_wc],rdx\n" +
        "      movsd m_real [reg_ra],ra\n      ldmxcsr [mxcsr_set]\n" +
        "      and   rsp,0xfffffffffffffff0\n      sub   rsp,32\n      call  %2\n" +
        "      movsd ra,m_real [reg_ra]\n" +
        "      mov   rcx,m_word [save_wa]\n      mov   rdx,m_word [save_wc]\n" +
        "      mov   rsp,rbp\n      pop   rbp\n      ret\n%endmacro";

    public static string Preprocess(string s)
    {
        // Normalize CRLF so the literal replace below is line-ending agnostic.
        s = s.Replace("\r\n", "\n");

        // int_masm.h replaces the %include and supplies the abstract layer.
        s = Regex.Replace(s, @"(?m)^\s*%include\s+""int\.h"".*\n", "");

        // Resolve compile-time config blocks (setreal=0, z_trace undefined -> drop).
        s = Regex.Replace(s, @"%if\s+setreal\s*==\s*1.*?%endif", "", RegexOptions.Singleline);
        s = Regex.Replace(s, @"%ifdef\s+z_trace.*?%endif",       "", RegexOptions.Singleline);

        // `syscall` is the SYSCALL instruction mnemonic in MASM; rename the macro.
        // \bsyscall\b leaves syscall_init / syscall_exit alone (underscore = word char).
        s = Regex.Replace(s, @"\bsyscall\b", "syscallm");

        // ABI fix 1: allocate 32B MS x64 shadow space AND free it (caller cleanup).
        s = s.Replace(
            "      and   rsp,0xfffffffffffffff0   ; 16byte alignment\n      call  %1\n",
            "      and   rsp,0xfffffffffffffff0   ; 16byte alignment\n" +
            "      sub   rsp,32                   ; MS x64 shadow space\n" +
            "      call  %1\n" +
            "      add   rsp,32                   ; free MS x64 shadow space (caller cleanup)\n");

        // ABI fix 2: replace the math_op macro with the MS x64 version.
        s = Regex.Replace(s, @"%macro\s+math_op\s+2.*?%endmacro", MathOp, RegexOptions.Singleline);

        return s;
    }

    // Splice int.dcl into the generated sbl.asm, mirroring asm.sbl's
    // include('int.dcl'). Two adjustments make it assemble under ml64:
    //   * drop the externs that masm.h already declares as data with a fixed
    //     type (_rc_/zeron/lowspminx/mxcsr_set) -- a second EXTERN with the
    //     converter's default PROC type would conflict;
    //   * label the type-word table `typet:` -- int.dcl declares `global typet`
    //     but never gives the table a defining label (NASM tolerates it; ml64
    //     does not).
    public static string SpliceIntDcl(string sblAsm, string dclText)
    {
        var dropExtern = new System.Collections.Generic.HashSet<string>
            { "_rc_", "zeron", "lowspminx", "mxcsr_set" };
        var sb = new System.Text.StringBuilder();
        foreach (var raw in dclText.Replace("\r\n", "\n").Split('\n'))
        {
            var m = Regex.Match(raw, @"^\s*extern\s+(\w+)\s*$");
            if (m.Success && dropExtern.Contains(m.Groups[1].Value)) continue;
            string l = raw;
            if (Regex.IsMatch(l, @"^\s*d_word\s+b_art\b") && l.Contains("type word - 0"))
                l = "typet:" + l;
            sb.Append(l).Append('\n');
        }
        return sblAsm.TrimEnd('\n') + "\n\n; ==== int.dcl (include) ====\n" + sb.ToString();
    }
}
